import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { ScrollToTop } from "@/components/ScrollToTop";
import CookieConsent from "../components/CookieConsent";
import GAClientPageViews from "@/components/GAClientPageViews";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="frame antialiased">
        <div className="app-shell">
          <ErrorReporter />
          {/* Google tag with Consent Mode v2: default deny analytics until user accepts */}
          <Script id="gtag-consent-init" strategy="beforeInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              // Set default consent to denied for analytics and ads
              gtag('consent', 'default', {
                'ad_storage': 'denied',
                'analytics_storage': 'denied',
                'ad_user_data': 'denied',
                'ad_personalization': 'denied',
                'functionality_storage': 'granted',
                'security_storage': 'granted'
              });
              gtag('js', new Date());
            `}
          </Script>
          {/* Load GA4 library. With consent default-denied, it will buffer until user grants analytics. */}
          <Script
            id="gtag-js"
            src="https://www.googletagmanager.com/gtag/js?id=G-2LYX6FZW6V"
            strategy="afterInteractive"
          />
          <Script id="gtag-config" strategy="beforeInteractive">
            {`
              if (typeof window !== 'undefined' && window.gtag) {
                // Do not auto send page_view until consent is granted
                window.gtag('config', 'G-2LYX6FZW6V', { send_page_view: false });
              }
            `}
          </Script>
          <Script
            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
            strategy="afterInteractive"
            data-target-origin="*"
            data-message-type="ROUTE_CHANGE"
            data-include-search-params="true"
            data-only-in-iframe="true"
            data-debug="true"
            data-custom-data='{"appName":"YourApp","version":"1.0.0","greeting":"hi"}'
          />
          {children}
          <ScrollToTop />
          <VisualEditsMessenger />
          <CookieConsent measurementId="G-2LYX6FZW6V" />
          <GAClientPageViews measurementId="G-2LYX6FZW6V" />
        </div>
      </body>
    </html>
  );
}
